{
 "title": "Indexer Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Project Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Successful Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(query_success_total) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failed Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(query_failure_total) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Container Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Coordinator Health Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coordinator_docker_stats_status{job=\"query_docker_stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Health Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_docker_stats_status{job=\"query_docker_stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Health Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_docker_stats_status{job=\"query_docker_stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Versions",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(coordinator_version) by (Time, coordinator_version)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(proxy_version) by (Time, proxy_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Coordinator Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coordinator_docker_stats_memory",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "db_docker_stats_memory", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Indexer Proxy Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "proxy_docker_stats_memory", "legendFormat": "__auto" }
   ]
  },
  { "title": "Cpu Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Coordinator Cpu Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "coordinator_docker_stats_cpu", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Postgres Cpu Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "db_docker_stats_cpu", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Indexer Proxy Cpu Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "proxy_docker_stats_cpu", "legendFormat": "__auto" }
   ]
  }
 ]
}