version: "3"

services:
  node_{{projectID}}:
    image: {{dockerRegistry}}:{{nodeVersion}}
    container_name: node_{{projectID}}
    restart: always
    environment:
      DB_USER: {{postgres.user}}
      DB_PASS: {{postgres.pass}}
      DB_DATABASE: {{postgres.db}}
      DB_HOST: {{postgres.host}}
      DB_PORT: {{postgres.port}}
    volumes:
      - /usr/projects/{{deploymentID}}:/home/projects/{{deploymentID}}
    command:
      - -f=ipfs://{{deploymentID}}
      - -d={{dictionary}}
      - --ipfs=https://authipfs.subquery.network/ipfs/api/v0
      - --network-endpoint={{{networkEndpoint}}}
      - --db-schema={{dbSchema}}
      - --port={{servicePort}}
      - --batch-size=50
      - --timeout=1800
      - --workers=3
      - --store-cache-threshold=300
      - --proof-of-index={{poiEnabled}}
      - -m=/home/projects/{{deploymentID}}/.mmr
      - --disable-historical={{disableHistorical}}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://node_{{projectID}}:{{servicePort}}/ready"
        ]
      interval: 3s
      timeout: 5s
      retries: 100

  query_{{projectID}}:
    image: onfinality/subql-query:{{queryVersion}}
    container_name: query_{{projectID}}
    ports:
      - {{servicePort}}:{{servicePort}}
    depends_on:
      "node_{{projectID}}":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: {{postgres.user}}
      DB_PASS: {{postgres.pass}}
      DB_DATABASE: {{postgres.db}}
      DB_HOST: {{postgres.host}}
      DB_PORT: {{postgres.port}}
    command:
      - --name={{dbSchema}}
      - --playground
      - --indexer=http://node_{{projectID}}:{{servicePort}}
      - --port={{servicePort}}

networks:
  default:
    name: coordinator-service
