version: "3"

services:
  node_{{projectID}}:
    image: {{dockerRegistry}}:{{nodeVersion}}
    container_name: node_{{projectID}}
    restart: always
    cpus: {{cpu}}
    environment:
      DB_USER: {{postgres.user}}
      DB_PASS: {{postgres.pass}}
      DB_DATABASE: {{postgres.db}}
      DB_HOST: {{postgres.host}}
      DB_PORT: {{postgres.port}}
    volumes:
      - {{mmrPath}}/poi/{{deploymentID}}:{{mmrPath}}/poi/{{deploymentID}}
    command:
      - -f=ipfs://{{deploymentID}}
      - -d={{networkDictionary}}
      - --ipfs=https://authipfs.subquery.network/ipfs/api/v0
      - --network-endpoint={{{networkEndpoint}}}
      - --db-schema={{dbSchema}}
      - --port={{servicePort}}
      - --batch-size={{batchSize}}
      - --timeout={{timeout}}
      - --workers={{worker}}
      - --store-cache-threshold={{cache}}
      - --proof-of-index=true
      - -m={{mmrPath}}/poi/{{deploymentID}}/.mmr
      - --disable-historical=false
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://node_{{projectID}}:{{servicePort}}/ready"
        ]
      interval: 3s
      timeout: 5s
      retries: 100

  query_{{projectID}}:
    image: onfinality/subql-query:{{queryVersion}}
    container_name: query_{{projectID}}
    ports:
      - {{servicePort}}:{{servicePort}}
    depends_on:
      "node_{{projectID}}":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: {{postgres.user}}
      DB_PASS: {{postgres.pass}}
      DB_DATABASE: {{postgres.db}}
      DB_HOST: {{postgres.host}}
      DB_PORT: {{postgres.port}}
    command:
      - --name={{dbSchema}}
      - --playground
      - --indexer=http://node_{{projectID}}:{{servicePort}}
      - --port={{servicePort}}

networks:
  default:
    name: {{dockerNetwork}}
