version: "3"

services:
  postgres:
    image: postgres:12-alpine
    container_name: indexer_db
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pos_z8X
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: indexer_cache
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  coordinator:
    container_name: indexer_coordinator
    image: coordinator:latest
    build:
      context: ../../../
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      "postgres":
        condition: service_healthy
      "ipfs":
        condition: service_healthy
    restart: always
    volumes:
      - .projects:/usr/projects
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --network=testnet
      - --ws-endpoint=https://polygon-mumbai.infura.io/v3/4458cf4d1689497b9a38b1d6bbf05e78
      - --postgres-host=postgres
      - --postgres-password=pos_z8X
      # use the same password in the db config
      - --postgres-port=5432
      - --use-prerelease
      - --port=8000
      - --debug
      - --ipfs=http://indexer_ipfs:8080/api/v0/
      - --mmrPath=/home
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-i",
          "-X POST",
          "http://indexer_coordinator:8000/graphql",
          "-H 'Content-Type: application/json'",
          "-d '{ \"query\": \"query { accountMetadata { network } }\" }'"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  proxy:
    image: subquerynetwork/indexer-proxy:latest
    container_name: indexer_proxy
    ports:
      - 8001:8001
    depends_on:
      "coordinator":
        condition: service_healthy
    restart: always
    command:
      - --port=8001
      - --auth
      - --debug
      - --jwt-secret=vOVH6sdmpNWjRRIqCc7rdxs
      - --network=testnet
      - --network-endpoint=https://moonbeam-alpha.api.onfinality.io/public
      - --redis-endpoint=redis://indexer_cache
      - --token-duration=8 # query auth token validity [hours]
      - --secret-key=vOVH6sdmpNWjRRIqCc7rdxs01lwHzfr3
      - --service-url=http://indexer_coordinator:8000
      - --bootstrap=/ip4/210.55.152.69/tcp/7370
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8001/healthy >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  ipfs:
    image: ipfs/kubo:master-2023-07-20-1fe17a4
    container_name: indexer_ipfs
    volumes:
      - .ipfs/export:/export
      - .ipfs/data:/data/ipfs
      - ./ipfs.sh:/container-init.d/ipfs.sh
    ports:
      - 4001:4001
      - 4001:4001/udp
      - 127.0.0.1:5001:5001
    expose:
      - 8080

networks:
  default:
    name: indexer_services