name: "Proxy-Docker-Prod"

on:
  workflow_dispatch:

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
          token: ${{ secrets.REPO_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: subquerynetwork
          password: ${{ secrets.SQ_DOCKERHUB_TOKEN }}

      ## node
      - name: Get updated coordinator version
        id: fetch-version
        run: |
          sh .github/workflows/scripts/proxyVersion.sh

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: amd64,arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./apps/indexer-proxy/proxy/Dockerfile
          tags: subquerynetwork/indexer-proxy:v${{ steps.fetch-version.outputs.VERSION }}
          build-args: RELEASE_VERSION=${{ steps.fetch-version.outputs.VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
